language: python
python:
  - "2.7"
  - "3.5"

env:
  - ANSIBLE_VERSION=2.4
  - ANSIBLE_VERSION=2.5
  - ANSIBLE_VERSION=2.6
  - ANSIBLE_VERSION=2.7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz python-setuptools
  - pip install -U pip setuptools wheel

install:
  - pip install -q -U -r requirements_tests.txt
  - pip install -q ansible==$ANSIBLE_VERSION
  - pip freeze

script:
  - make test
  - make test_install ANSIBLE_VERSION=$ANSIBLE_VERSION

after_success:
  - pip install -U coveralls
  - coveralls
