language: python
python:
  - "2.7"
  - "3.5"

env:
  - ANSIBLE_VERSION=2.4
  - ANSIBLE_VERSION=2.5
  - ANSIBLE_VERSION=2.6
  - ANSIBLE_VERSION=2.7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
  - pip install -U pip

install:
  - pip install -q -U -r requirements_tests.txt
  - pip install -q ansible==$ANSIBLE_VERSION
  - pip freeze

script:
  - make test

after_success:
  - coveralls
